# Generated by Django 4.2.5 on 2024-04-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Reserved'), ('o', 'On loan'), ('m', 'Maintenance'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
