# Generated by Django 4.2.5 on 2024-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('r', 'Reserved'), ('a', 'Available')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
