# Generated by Django 5.0.4 on 2024-04-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On loan'), ('r', 'Reserved'), ('m', 'Maintenance')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
